// spells
export const SPELLS_HAS_ERRORED = 'SPELLS_HAS_ERRORED'
export const SPELLS_IS_LOADING = 'SPELLS_IS_LOADING'
export const SPELLS_FETCH_DATA_SUCCESS = 'SPELLS_FETCH_DATA_SUCCESS'
export const FILTER_SPELLS_BY_LEVEL = 'FILTER_SPELLS_BY_LEVEL'
export const FILTER_SPELLS_BY_SCHOOL = 'FILTER_SPELLS_BY_SCHOOL'
export const FILTER_SPELLS_BY_CLASS = 'FILTER_SPELLS_BY_CLASS'
export const CLEAR_SPELLS_LEVEL_FILTER = 'CLEAR_SPELLS_LEVEL_FILTER'
export const CLEAR_SPELLS_SCHOOL_FILTER = 'CLEAR_SPELLS_SCHOOL_FILTER'
export const CLEAR_SPELLS_CLASS_FILTER = 'CLEAR_SPELLS_CLASS_FILTER'
export const CLEAR_SPELLS_FILTERS = 'CLEAR_SPELLS_FILTERS'
export const UPDATE_SPELL_SEARCH_TERM = 'UPDATE_SPELL_SEARCH_TERM'
export const UPDATE_SPELLS_SORT = 'UPDATE_SPELLS_SORT'

// spellbook
export const TOGGLE_IN_SPELLBOOK = 'TOGGLE_IN_SPELLBOOK'
